import Head from 'next/head'
import Image from 'next/image'


export default function header()
{
    return(
        <div>
            <Head>
                <title>dAPP</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </div>
    );
}